AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/spec_helper.rb'

  Rails:
    Enabled: true
  DisplayCopNames: true
  DisplayStyleGuide: true

##################### Style ##################################

Style/AsciiComments:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/GuardClause:
  MinBodyLength: 5

Style/Documentation:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/ClassAndModuleChildren:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/RedundantSelf:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

##################### Lint ##################################

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

##################### Metrics ##################################
Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "db/migrate/*.rb"

Metrics/PerceivedComplexity:
  Max: 8
